config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'

  get  'tournament/new',                to: 'tournament#new'
  get  'tournament/leaderboard',        to: 'tournament#leaderboard'
  post 'tournament/vote/',              to: 'tournament#vote', as: :vote_tournament

end

app/models/leader.rb
class Leader < ActiveRecord::Base

  def self.store(image)
    leader = Leader.find_or_create_by(path: image)
    leader.count += 1
    leader.save
  end

end

app/models/photo.rb
require 'httparty'
class Photo

  def self.get
    response = HTTParty.get('http://pv.pop.umn.edu/images/')
    result = {status: :error, items: ""}
    if response.code.to_s == "200"
      result[:status] = :success
      result[:photos] = JSON.parse(response.body)["data"].map{|i| "'#{i}'"}.join(",")
    end
    result
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tournament_controller.rb
class TournamentController < ApplicationController

  before_action :authenticate_user!

  def new
    @photos = Photo.get
  end

  def leaderboard
    @leaders = Leader.order('count desc')
  end

  def vote
    Leader.store(params[:path])
    head :ok
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Choose a Photo
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags 
  body ng-app="TournamentApp"
    .navbar.navbar-inverse
      .navbar-header
        button.navbar-toggle data-target=".navbar-inverse-collapse" data-toggle="collapse" type="button" 
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to "Choose a Photo", root_path, class: "navbar-brand"
      .navbar-collapse.collapse.navbar-inverse-collapse
        ul.nav.navbar-nav
          - if user_signed_in?
            li class="#{request.original_url.include?('tournament/new') ? 'active' : ''}" 
              = link_to "Tournament", tournament_new_path, "data-no-turbolink" => true
            li class="#{request.original_url.include?('tournament/leaderboard') ? 'active' : ''}" 
              = link_to "Photo Leaderboard", tournament_leaderboard_path          
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            li class="#{request.original_url.include?('users/edit') ? 'active' : ''}" 
              = link_to "Profile", edit_user_registration_path
            li
              = link_to "Logout", destroy_user_session_path, method: :delete
          - else
            li class="#{request.original_url.include?('users/sign_in') ? 'active' : ''}" 
              = link_to "Sign In", new_user_session_path
            li class="#{request.original_url.include?('users/sign_up') ? 'active' : ''}" 
              = link_to "Sign Up", new_user_registration_path  
    .container          
      = yield 

app/views/tournament/_photo.html.slim
- index ||= 0
a.thumbnail href="#" ng-click="voteFor(photos[#{index}])"
  img ng-src="{{photos[#{index}]}}"

app/views/tournament/leaderboard.html.slim
h1 Photo Leaderboard

- @leaders.each do |leader|
  .thumbnail
    img src="#{leader.path}"
    .caption
      p = "Voted: #{leader.count} times"

app/views/tournament/new.html.slim
h1 Tournament

div ng-controller="TournamentController" ng-init="photos = [#{@photos[:photos]}]; startRound();"

  - if @photos[:status] == :error
    .alert.alert-dismissable.alert-danger
      h4 Error
      p 
        | Some error occured. Please, try to refresh the  
        = link_to "page", tournament_new_path, class: 'alert-link'
        | .

  - if @photos[:status] == :success
    .alert.alert-dismissable.alert-success ng-if="selected.length == 1 && photos.length == 0"
      h4 Congratulation
      p Wow! You have finished the tournament.

    div ng-if="!(selected.length == 1 && photos.length == 0)"
      h3 
        | Round 
        span ng-bind="round"
      p Choose between 2 photos. Which do you like more?
      .row
        .col-md-4
          = render 'tournament/photo', index: 0
        .col-md-4
          = render 'tournament/photo', index: 1

    .well ng-if="selected.length == 1 && photos.length == 0"

      h2 This is the Winner!

      p
        img ng-src="{{selected[0]}}"

      p
        = link_to "Start again", tournament_new_path, class: "btn btn-success"

app/views/welcome/index.html.slim
.jumbotron
  h1 Welcome
  p This is a Photo Voting Tournament App. 

  p
    - if user_signed_in? 
      = link_to "Start Tournament", tournament_new_path, class: "btn btn-primary btn-lg"
    - else
      = link_to "Sign In", new_user_session_path, class: "btn btn-primary btn-lg"